### ISSUE TITLE
objects (buildings, hoods) not clickable anymore in 3d Scene 

### ISSUE THREAD

**Issue by tommuelli** [canoo/code-of-gotham#27]
commit : 4b0dacafca44a8b532f8198ffb7a86051d2a5aa6 
brings a bug by using a StackPane that puts the 2d Scene on top of the 3d Scene. Left mouse-click and hoover don't work anymore for buildings and hoods. Going back to BorderPane would fix it, but doesn't look that good

**Comment by maxflow7934** [comment]
Fixed on master.
